/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppHeader: typeof import('./src/components/AppHeader.vue')['default']
    CustomErrorMessage: typeof import('./src/components/CustomErrorMessage.vue')['default']
    CustomFormField: typeof import('./src/components/CustomFormField.vue')['default']
    ErrorWrapper: typeof import('./src/components/ErrorWrapper.vue')['default']
    LoadingSpinner: typeof import('./src/components/LoadingSpinner.vue')['default']
    MyPostCard: typeof import('./src/components/MyPostCard.vue')['default']
    PasswordInput: typeof import('./src/components/PasswordInput.vue')['default']
    PostCard: typeof import('./src/components/PostCard.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
